import { Scalar } from "@scalar/hono-api-reference";

export const scalar = Scalar({
	theme: "kepler",
	showSidebar: true,
	hideClientButton: true,
	showDeveloperTools: "never",
	url: "/api/v1/openapi.json",
	operationTitleSource: "summary",
	persistAuth: false,
	telemetry: true,
	externalUrls: {
		dashboardUrl: "https://dashboard.scalar.com",
		registryUrl: "https://registry.scalar.com",
		proxyUrl: "https://proxy.scalar.com",
		apiBaseUrl: "https://api.scalar.com",
	},
	layout: "modern",
	isEditable: false,
	isLoading: false,
	hideModels: false,
	documentDownloadType: "both",
	hideTestRequestButton: false,
	hideSearch: false,
	showOperationId: true,
	hideDarkModeToggle: false,
	withDefaultFonts: true,
	defaultOpenFirstTag: true,
	defaultOpenAllTags: false,
	expandAllModelSections: false,
	expandAllResponses: false,
	orderSchemaPropertiesBy: "alpha",
	orderRequiredPropertiesFirst: true,
	_integration: "hono",
	default: false,
	slug: "sind-invoices-api",
	title: "SIND Invoices API",
	pageTitle: "SIND Invoices API Reference",
	agent: {
		disabled: true,
	},
});
