/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSalesRouteImport } from './routes/dashboard/sales'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardLedgerRouteImport } from './routes/dashboard/ledger'
import { Route as DashboardJournalRouteImport } from './routes/dashboard/journal'
import { Route as DashboardReportsDreRouteImport } from './routes/dashboard/reports/dre'
import { Route as DashboardReportsCurrentLiquidityRouteImport } from './routes/dashboard/reports/current-liquidity'
import { Route as DashboardReportsBalanceSheetRouteImport } from './routes/dashboard/reports/balance-sheet'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalesRoute = DashboardSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedgerRoute = DashboardLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJournalRoute = DashboardJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsDreRoute = DashboardReportsDreRouteImport.update({
  id: '/reports/dre',
  path: '/reports/dre',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsCurrentLiquidityRoute =
  DashboardReportsCurrentLiquidityRouteImport.update({
    id: '/reports/current-liquidity',
    path: '/reports/current-liquidity',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsBalanceSheetRoute =
  DashboardReportsBalanceSheetRouteImport.update({
    id: '/reports/balance-sheet',
    path: '/reports/balance-sheet',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/ledger': typeof DashboardLedgerRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/reports/balance-sheet': typeof DashboardReportsBalanceSheetRoute
  '/dashboard/reports/current-liquidity': typeof DashboardReportsCurrentLiquidityRoute
  '/dashboard/reports/dre': typeof DashboardReportsDreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/ledger': typeof DashboardLedgerRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/reports/balance-sheet': typeof DashboardReportsBalanceSheetRoute
  '/dashboard/reports/current-liquidity': typeof DashboardReportsCurrentLiquidityRoute
  '/dashboard/reports/dre': typeof DashboardReportsDreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/ledger': typeof DashboardLedgerRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/reports/balance-sheet': typeof DashboardReportsBalanceSheetRoute
  '/dashboard/reports/current-liquidity': typeof DashboardReportsCurrentLiquidityRoute
  '/dashboard/reports/dre': typeof DashboardReportsDreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/dashboard/journal'
    | '/dashboard/ledger'
    | '/dashboard/products'
    | '/dashboard/sales'
    | '/dashboard/'
    | '/dashboard/reports/balance-sheet'
    | '/dashboard/reports/current-liquidity'
    | '/dashboard/reports/dre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/dashboard/journal'
    | '/dashboard/ledger'
    | '/dashboard/products'
    | '/dashboard/sales'
    | '/dashboard'
    | '/dashboard/reports/balance-sheet'
    | '/dashboard/reports/current-liquidity'
    | '/dashboard/reports/dre'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/dashboard/journal'
    | '/dashboard/ledger'
    | '/dashboard/products'
    | '/dashboard/sales'
    | '/dashboard/'
    | '/dashboard/reports/balance-sheet'
    | '/dashboard/reports/current-liquidity'
    | '/dashboard/reports/dre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sales': {
      id: '/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof DashboardSalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger': {
      id: '/dashboard/ledger'
      path: '/ledger'
      fullPath: '/dashboard/ledger'
      preLoaderRoute: typeof DashboardLedgerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/journal': {
      id: '/dashboard/journal'
      path: '/journal'
      fullPath: '/dashboard/journal'
      preLoaderRoute: typeof DashboardJournalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/dre': {
      id: '/dashboard/reports/dre'
      path: '/reports/dre'
      fullPath: '/dashboard/reports/dre'
      preLoaderRoute: typeof DashboardReportsDreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/current-liquidity': {
      id: '/dashboard/reports/current-liquidity'
      path: '/reports/current-liquidity'
      fullPath: '/dashboard/reports/current-liquidity'
      preLoaderRoute: typeof DashboardReportsCurrentLiquidityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/balance-sheet': {
      id: '/dashboard/reports/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/dashboard/reports/balance-sheet'
      preLoaderRoute: typeof DashboardReportsBalanceSheetRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardJournalRoute: typeof DashboardJournalRoute
  DashboardLedgerRoute: typeof DashboardLedgerRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardSalesRoute: typeof DashboardSalesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardReportsBalanceSheetRoute: typeof DashboardReportsBalanceSheetRoute
  DashboardReportsCurrentLiquidityRoute: typeof DashboardReportsCurrentLiquidityRoute
  DashboardReportsDreRoute: typeof DashboardReportsDreRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardJournalRoute: DashboardJournalRoute,
  DashboardLedgerRoute: DashboardLedgerRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardSalesRoute: DashboardSalesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardReportsBalanceSheetRoute: DashboardReportsBalanceSheetRoute,
  DashboardReportsCurrentLiquidityRoute: DashboardReportsCurrentLiquidityRoute,
  DashboardReportsDreRoute: DashboardReportsDreRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
