import { timestamps } from "@api/db/customTypes/timestamps";
import type { OmitAutoGeneratedCols } from "@api/db/database.defs";
import { companies } from "@api/db/schema/companies";
import type { AccountType } from "@api/features/accounts/accountTypes";
import { type AnyPgColumn, integer, pgTable, serial, varchar } from "drizzle-orm/pg-core";

export type AccountCategory = "assets" | "liabilities" | "equity" | "revenue" | "expenses";
export type AccountNature = "credit" | "debit";

export const accounts = pgTable("accounts", {
  id: serial().primaryKey(),

  name: varchar().notNull(),
  type: varchar().notNull().$type<AccountType>(),
  description: varchar(),

  category: varchar().notNull().$type<AccountCategory>(),
  nature: varchar().notNull().$type<AccountNature>(),

  parentId: integer().references((): AnyPgColumn => accounts.id, {
    onDelete: "restrict",
  }),

  companyId: integer()
    .notNull()
    .references(() => companies.id, {
      onDelete: "cascade",
    }),

  ...timestamps,
});

export type InsertAccount = OmitAutoGeneratedCols<typeof accounts.$inferInsert>;
export type Account = typeof accounts.$inferSelect;
