import { timestamps } from "@api/db/customTypes/timestamps";
import type { OmitAutoGeneratedCols } from "@api/db/database.defs";
import type { Account, AccountCategory } from "@api/db/schema/accounts";
import type { AccountType } from "@api/features/accounts/accountTypes";
import { jsonb, pgTable, serial, varchar } from "drizzle-orm/pg-core";

export type AccountInChart = Pick<Account, "name" | "description" | "nature" | "type"> & {
  children?: AccountInChart[];
};

export const accountsCharts = pgTable("accounts_charts", {
  id: serial().primaryKey(),

  name: varchar().notNull().unique(),
  description: varchar(),

  chart: jsonb().notNull().$type<Record<AccountCategory, AccountInChart[]>>(),

  ...timestamps,
});

export type InsertAccountsChart = OmitAutoGeneratedCols<typeof accountsCharts.$inferInsert>;
export type AccountsChart = typeof accountsCharts.$inferSelect;
