import { timestamps } from "@api/db/customTypes/timestamps";
import type { OmitAutoGeneratedCols } from "@api/db/database.defs";
import { user } from "@api/db/schema/auth";
import { char, pgTable, serial, text, varchar } from "drizzle-orm/pg-core";

export const companies = pgTable("companies", {
  id: serial().primaryKey(),

  name: varchar().notNull(),
  cnpj: char({ length: 14 }).unique(),

  userId: text()
    .notNull()
    .references(() => user.id, {
      onDelete: "cascade",
    }),

  ...timestamps,
});

export type InsertCompany = OmitAutoGeneratedCols<typeof companies.$inferInsert>;
export type Company = typeof companies.$inferSelect;
