import { timestamps } from "@api/db/customTypes/timestamps";
import type { OmitAutoGeneratedCols } from "@api/db/database.defs";
import { accounts } from "@api/db/schema/accounts";
import { companies } from "@api/db/schema/companies";
import { integer, numeric, pgTable, serial, timestamp, varchar } from "drizzle-orm/pg-core";

export type JournalSourceType = "sale" | "receipt" | "stock_issue" | "manual" | "reversal";
export type JournalEntryStatus = "posted" | "void";
export type JournalEntryLineType = "debit" | "credit";

export const journalEntries = pgTable("journal_entries", {
  id: serial().primaryKey(),

  companyId: integer()
    .notNull()
    .references(() => companies.id, {
      onDelete: "cascade",
    }),

  sourceType: varchar().notNull().$type<JournalSourceType>(),
  sourceId: integer(),
  entryDate: timestamp().notNull(),
  memo: varchar(),
  status: varchar().notNull().$type<JournalEntryStatus>(),

  ...timestamps,
});

export const journalEntryLines = pgTable("journal_entry_lines", {
  id: serial().primaryKey(),

  entryId: integer()
    .notNull()
    .references(() => journalEntries.id, {
      onDelete: "cascade",
    }),

  accountId: integer()
    .notNull()
    .references(() => accounts.id, {
      onDelete: "restrict",
    }),

  type: varchar().notNull().$type<JournalEntryLineType>(),
  amount: numeric({ precision: 14, scale: 2 }).notNull(),
  description: varchar(),
});

export type InsertJournalEntry = OmitAutoGeneratedCols<typeof journalEntries.$inferInsert>;
export type JournalEntry = typeof journalEntries.$inferSelect;
export type InsertJournalEntryLine = OmitAutoGeneratedCols<typeof journalEntryLines.$inferInsert>;
export type JournalEntryLine = typeof journalEntryLines.$inferSelect;
