import { timestamps } from "@api/db/customTypes/timestamps";
import type { OmitAutoGeneratedCols } from "@api/db/database.defs";
import { companies } from "@api/db/schema/companies";
import { boolean, integer, numeric, pgTable, serial, varchar } from "drizzle-orm/pg-core";

export type ProductType = "product" | "service";
export type ProductCostMethod = "average_cost";

export const products = pgTable("products", {
  id: serial().primaryKey(),

  companyId: integer()
    .notNull()
    .references(() => companies.id, {
      onDelete: "cascade",
    }),

  name: varchar().notNull(),
  type: varchar().notNull().$type<ProductType>(),
  defaultSalePrice: numeric({ precision: 14, scale: 2 }).notNull(),
  trackInventory: boolean().notNull().default(false),
  costMethod: varchar().notNull().$type<ProductCostMethod>().default("average_cost"),
  isActive: boolean().notNull().default(true),

  ...timestamps,
});

export type InsertProduct = OmitAutoGeneratedCols<typeof products.$inferInsert>;
export type Product = typeof products.$inferSelect;
