import { timestamps } from "@api/db/customTypes/timestamps";
import type { OmitAutoGeneratedCols } from "@api/db/database.defs";
import { accounts } from "@api/db/schema/accounts";
import { companies } from "@api/db/schema/companies";
import { sales } from "@api/db/schema/sales";
import { integer, numeric, pgTable, serial, timestamp, varchar } from "drizzle-orm/pg-core";

export const receipts = pgTable("receipts", {
  id: serial().primaryKey(),

  companyId: integer()
    .notNull()
    .references(() => companies.id, {
      onDelete: "cascade",
    }),

  saleId: integer()
    .notNull()
    .references(() => sales.id, {
      onDelete: "restrict",
    }),

  receiptDate: timestamp().notNull(),
  amount: numeric({ precision: 14, scale: 2 }).notNull(),

  cashAccountId: integer()
    .notNull()
    .references(() => accounts.id, {
      onDelete: "restrict",
    }),

  notes: varchar(),

  ...timestamps,
});

export type InsertReceipt = OmitAutoGeneratedCols<typeof receipts.$inferInsert>;
export type Receipt = typeof receipts.$inferSelect;
