import { timestamps } from "@api/db/customTypes/timestamps";
import type { OmitAutoGeneratedCols } from "@api/db/database.defs";
import { companies } from "@api/db/schema/companies";
import { products } from "@api/db/schema/products";
import { integer, numeric, pgTable, serial, timestamp, varchar } from "drizzle-orm/pg-core";

export type SaleKind = "product" | "service" | "mixed";
export type SalePaymentTerms = "cash" | "credit";
export type SaleStatus = "posted" | "void";
export type SaleItemType = "product" | "service";

export const sales = pgTable("sales", {
  id: serial().primaryKey(),

  companyId: integer()
    .notNull()
    .references(() => companies.id, {
      onDelete: "cascade",
    }),

  kind: varchar().notNull().$type<SaleKind>(),
  paymentTerms: varchar().notNull().$type<SalePaymentTerms>(),
  issueDate: timestamp().notNull(),
  description: varchar(),
  customerName: varchar(),
  grossAmount: numeric({ precision: 14, scale: 2 }).notNull(),
  discountAmount: numeric({ precision: 14, scale: 2 }).notNull(),
  netAmount: numeric({ precision: 14, scale: 2 }).notNull(),
  status: varchar().notNull().$type<SaleStatus>(),

  ...timestamps,
});

export const saleItems = pgTable("sale_items", {
  id: serial().primaryKey(),

  saleId: integer()
    .notNull()
    .references(() => sales.id, {
      onDelete: "cascade",
    }),

  productId: integer().references(() => products.id, {
    onDelete: "restrict",
  }),

  description: varchar().notNull(),
  type: varchar().notNull().$type<SaleItemType>(),
  quantity: numeric({ precision: 14, scale: 3 }).notNull(),
  unitPrice: numeric({ precision: 14, scale: 2 }).notNull(),
  lineAmount: numeric({ precision: 14, scale: 2 }).notNull(),
  unitCostSnapshot: numeric({ precision: 14, scale: 2 }),
  lineCostAmount: numeric({ precision: 14, scale: 2 }),
});

export type InsertSale = OmitAutoGeneratedCols<typeof sales.$inferInsert>;
export type Sale = typeof sales.$inferSelect;
export type InsertSaleItem = OmitAutoGeneratedCols<typeof saleItems.$inferInsert>;
export type SaleItem = typeof saleItems.$inferSelect;
