import { timestamps } from "@api/db/customTypes/timestamps";
import type { OmitAutoGeneratedCols } from "@api/db/database.defs";
import { companies } from "@api/db/schema/companies";
import { products } from "@api/db/schema/products";
import { integer, numeric, pgTable, serial, timestamp, varchar } from "drizzle-orm/pg-core";

export type StockMovementType = "purchase" | "sale_issue" | "adjustment";
export type StockMovementSourceType = "sale" | "manual" | "purchase" | "adjustment";

export const stockMovements = pgTable("stock_movements", {
  id: serial().primaryKey(),

  companyId: integer()
    .notNull()
    .references(() => companies.id, {
      onDelete: "cascade",
    }),

  productId: integer()
    .notNull()
    .references(() => products.id, {
      onDelete: "restrict",
    }),

  type: varchar().notNull().$type<StockMovementType>(),
  quantity: numeric({ precision: 14, scale: 3 }).notNull(),
  unitCost: numeric({ precision: 14, scale: 2 }).notNull(),
  totalCost: numeric({ precision: 14, scale: 2 }).notNull(),
  date: timestamp().notNull(),
  sourceType: varchar().notNull().$type<StockMovementSourceType>(),
  sourceId: integer(),

  ...timestamps,
});

export type InsertStockMovement = OmitAutoGeneratedCols<typeof stockMovements.$inferInsert>;
export type StockMovement = typeof stockMovements.$inferSelect;
